apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialecho
  labels:
    app: socialecho
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socialecho
  template:
    metadata:
      labels:
        app: socialecho
    spec:
      containers:
      - name: socialecho
        image: hayat126/my-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"