apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialecho
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: hayat126/my-app:latest
        ports:
        - containerPort: 5000

