apiVersion: v1
kind: Service
metadata:
  name: socialecho-service
  namespace: my-app-namespace  # Corrected here
  labels:
    app: socialecho
spec:
  type: NodePort
  selector:
    app: socialecho  # Keep this once
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001