name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        minikube docker-env | Invoke-Expression

    - name: Build Docker image
      run: |
        docker build -t hayat126/my-app:latest .

    - name: Login to Docker Hub
      run: echo ArwaAhmed1234$ | docker login -u hayat126 --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push hayat126/my-app:latest

    - name: Verify kubectl is using Minikube context
      run: |
        kubectl config use-context minikube
        kubectl config current-context

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: Check Pods Status
      run: kubectl get pods -n my-app-namespace

    - name: Check Pods Logs
      run: kubectl logs -l app=my-app -n my-app-namespace
